FROM adoptopenjdk:11-jdk

RUN apt update
RUN apt install -y openssh-server
RUN sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

# TODO: add a user that can log in and has root privs
# Can crib from https://github.com/vertigobr/tiny-sshd/blob/master/Dockerfile

COPY spring-petclinic-rest/ /app/spring-petclinic-rest/
COPY bin/ /app/bin/

WORKDIR /app/spring-petclinic-rest

RUN ./mvnw install

WORKDIR /app
EXPOSE 9966

ENTRYPOINT ["bin/run-app-with-agent.sh"]
