FROM adoptopenjdk:11-jdk

COPY spring-petclinic-rest/ /app/spring-petclinic-rest/
COPY bin/ /app/bin/

WORKDIR /app/spring-petclinic-rest

RUN ./mvnw install

WORKDIR /app
EXPOSE 9966

ENTRYPOINT ["bin/run-app-with-agent.sh"]
